// Generated by CoffeeScript 1.3.3
var SimpleMethod;

SimpleMethod = (function() {

  function SimpleMethod(object) {
    var label, p, _i, _len, _ref;
    this.probabilities = [];
    this.labelmap = [];
    for (label in object) {
      if (object.hasOwnProperty(label)) {
        this.labelmap.push(label);
        this.probabilities.push(object[label]);
      }
    }
    this.sum = 0;
    _ref = this.probabilities;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      this.sum += p;
    }
  }

  SimpleMethod.prototype.next = function() {
    var i, num, p;
    num = this.sum * Math.random();
    p = 0;
    i = 0;
    while (true) {
      p += this.probabilities[i];
      if (num < p) {
        return this.labelmap[i];
      }
      i++;
    }
  };

  return SimpleMethod;

})();
